import {
  Bar,
  CartesianGrid,
  ComposedChart,
  Line,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts'
import { Link } from 'react-router-dom'
import { ChartCard } from '../components/ChartCard'
import { PageHeader } from '../components/Layout'
import { AXIS_PROPS, defaultTooltip } from '../components/charts'
import { useRows } from '../hooks/useQuery'
import { fmtInt, fmtPct, titleCase } from '../lib/format'
import { LOCKOUT_RATE, PARETO } from '../lib/queries'

type ParetoRow = {
  contact_reason: string
  contacts: number
  share_pct: number
  cumulative_pct: number
}

type LockoutRate = {
  blocked_orders: number
  false_positives: number
  lockout_contacts: number
  lockouts_from_good_customers: number
  contacts_per_1000_blocked: number
  contacts_per_1000_false_positives: number
}

export function RootCause() {
  const { rows } = useRows<ParetoRow>(PARETO)
  const rate = useRows<LockoutRate>(LOCKOUT_RATE).rows[0]

  return (
    <div className="space-y-4">
      <PageHeader
        title="Root cause attribution"
        lede="What is actually driving contacts? A Pareto view, then the attribution the volume chart can't show you: a chunk of these contacts are self-inflicted — generated by our own fraud rules blocking legitimate customers."
      />

      <ChartCard
        title="Contact drivers, Pareto view"
        subtitle="Bars: share of all contacts per reason. Line: cumulative share — the top 5 reasons cover well over half of everything."
        sql={PARETO}
      >
        <ResponsiveContainer width="100%" height={300}>
          <ComposedChart data={rows} margin={{ top: 8, right: 8, bottom: 44, left: -12 }}>
            <CartesianGrid vertical={false} />
            <XAxis
              dataKey="contact_reason"
              {...AXIS_PROPS}
              interval={0}
              angle={-38}
              textAnchor="end"
              tickFormatter={(r: string) => titleCase(r)}
              height={70}
              tick={{ fontSize: 10.5 }}
            />
            <YAxis {...AXIS_PROPS} unit="%" domain={[0, 100]} />
            <Tooltip content={defaultTooltip((_k, v) => fmtPct(v))} cursor={{ fill: 'var(--grid)', opacity: 0.4 }} />
            <Bar dataKey="share_pct" name="Share" fill="var(--s1)" radius={[4, 4, 0, 0]} maxBarSize={26} />
            <Line
              type="monotone"
              dataKey="cumulative_pct"
              name="Cumulative"
              stroke="var(--s2)"
              strokeWidth={2}
              dot={{ r: 2.5, fill: 'var(--s2)' }}
            />
          </ComposedChart>
        </ResponsiveContainer>
        <div className="mt-1 flex gap-4 text-[12px] text-ink-2">
          <span><span className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[var(--s1)]" />Share of contacts</span>
          <span><span className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[var(--s2)]" />Cumulative share</span>
        </div>
      </ChartCard>

      <ChartCard
        title="The self-inflicted category: fraud-rule lockouts"
        subtitle="Joining contacts to the orders that triggered them attributes “account locked” volume directly to fraud decisioning — the cross-module insight a per-reason count can't surface."
        sql={LOCKOUT_RATE}
        footnote="These are the same rows the decisioning simulator counts as false positives at baseline thresholds — the numbers match by construction, not coincidence. Tightening rules moves this figure; the simulator projects it live."
      >
        {rate && (
          <div className="grid gap-3 sm:grid-cols-3">
            <div className="rounded-lg border border-line px-4 py-3">
              <p className="text-[12px] text-muted">Blocked orders (baseline rule)</p>
              <p className="tnum mt-1 text-[24px] font-semibold text-ink">{fmtInt(rate.blocked_orders)}</p>
              <p className="mt-1 text-[12px] text-ink-2">
                of which <span className="tnum font-semibold">{fmtInt(rate.false_positives)}</span> are legitimate
              </p>
            </div>
            <div className="rounded-lg border border-line px-4 py-3">
              <p className="text-[12px] text-muted">Lockout contacts generated</p>
              <p className="tnum mt-1 text-[24px] font-semibold text-ink">{fmtInt(rate.lockout_contacts)}</p>
              <p className="mt-1 text-[12px] text-ink-2">
                <span className="tnum font-semibold">{fmtInt(rate.lockouts_from_good_customers)}</span> from good
                customers
              </p>
            </div>
            <div className="rounded-lg border border-line px-4 py-3">
              <p className="text-[12px] text-muted">Contacts per 1,000 blocked orders</p>
              <p className="tnum mt-1 text-[24px] font-semibold text-ink">{fmtInt(rate.contacts_per_1000_blocked)}</p>
              <p className="mt-1 text-[12px] text-ink-2">
                {fmtInt(rate.contacts_per_1000_false_positives)} per 1,000 false positives
              </p>
            </div>
          </div>
        )}
        <p className="mt-4 max-w-prose text-[13.5px] leading-relaxed text-ink-2">
          Read it this way: every 1,000 orders the rules block buys us{' '}
          {rate ? fmtInt(rate.contacts_per_1000_blocked) : '…'} support conversations, almost none of which automation
          can resolve (lockouts run ~10% automated resolution vs 46% overall, at the longest handle times of any
          non-dispute reason). Half of the blocked-legitimate customers simply leave without contacting us at all —
          silent churn this dataset can only bound, not measure. Try the trade-off yourself in the{' '}
          <Link to="/simulator" className="font-medium text-[var(--s1)] hover:underline">
            decisioning simulator
          </Link>
          .
        </p>
      </ChartCard>
    </div>
  )
}
